name: Nippo Generator
on:
  schedule:
    - cron: "11 15 * * *"
  workflow_dispatch:
jobs:
  notion-daily-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm start
        env:
          TZ: "Asia/Tokyo"
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          TOGGL_TRACK_API_TOKEN: ${{ secrets.TOGGL_TRACK_API_TOKEN }}
